export const SCREEN = {
    FAJNY_SCREEN: '',
    TOURNAMENTLIST: 'Wydarzenia',
    ACTIVITYINDICATOR: 'ActivityIndicatorScreen',
    HEADER:'Header',
    LOGIN:'LoginScreen',
    MANAGER:'ManagerScreen',
    PASSWORDRECOVERY:'PasswordRecoveryScreen',
    PLAYER:'PlayerScreen',
    REGISTER:'RegisterScreen',
    USERSLIST: 'Użytkownicy',
    TOURNAMENTDETAILS: 'TournamentDetailsScreen',
    USERSDETAILS: 'UserDetailsScreen',
    ERROR: 'ErrorScreen',
};