export const SCREEN = {
    TOURNAMENTLIST: 'Lista Wydarzeń',
    ACTIVITYINDICATOR: 'ActivityIndicatorScreen',
    HEADER:'Header',
    LOGIN:'LoginScreen',
    MANAGER:'ManagerScreen',
    PASSWORDRECOVERY:'PasswordRecoveryScreen',
    PLAYER:'PlayerScreen',
    REGISTER:'RegisterScreen',
    USERSLIST: 'Lista Użytkowników',
    TOURNAMENTDETAILS: 'TournamentDetailsScreen',
    USERSDETAILS: 'UserDetailsScreen',
    ERROR: 'ErrorScreen',
    TICKETTYPES:'Rodzaje biletów',
    MYTICKETS: 'Moje bilety i rezerwacje',
    BOOKINGSLIST: 'Lista rezerwacji',
    MYPROFILE: 'Mój profil',
    MESSAGESLIST: 'Lista Wiadomości',
    MYMESSAGES: 'Moje wiadomości',
    MYTOURNAMENTS: 'Lista wydarzeń',
};