export const SCREEN = {
    TOURNAMENTLIST: 'Wydarzenia',
    ACTIVITYINDICATOR: 'ActivityIndicatorScreen',
    HEADER:'Header',
    LOGIN:'LoginScreen',
    MANAGER:'ManagerScreen',
    PASSWORDRECOVERY:'PasswordRecoveryScreen',
    PLAYER:'PlayerScreen',
    REGISTER:'RegisterScreen',
    USERSLIST: 'Użytkownicy',
    TOURNAMENTDETAILS: 'TournamentDetailsScreen',
    USERSDETAILS: 'UserDetailsScreen',
    ERROR: 'ErrorScreen',
    MYTICKETS: 'Moje Bilety',
    MYBOOKINGS: 'Moje Rezerwacje',
    MYMESSAGES: 'Wiadomości',
};